### ISSUE TITLE
add a memory with a photo

### ISSUE THREAD

**Issue by fetsorn** [anton-sviridov/suiwei#1]
user must save a digital image
user must save a description of the digital image
user must save a date
user must see a list of events

```shell
$ wget https://picsum.photos/200/300 -O event.jpg

$ suiwei record --file event.jpg --comment "happy day" --database db.sql --dir cache

# saves event.jpg to ./cache/event.jpg
# saves "happy day", today's date and "event.jpg" to ./cache/db.sql

$ suiwei remember
# 2024-07-21 happy day event.jpg
```

**Comment by anton-sviridov** [comment]
- set diesel to work with db — which backend?
- create db
- create table with 3 fields
  image: string
  description: string
  date: string

scrtipts to interact with table with cli commands:

-    ```$ suiwei record --file event.jpg --comment "happy day" --database db.sql```
→ check if db.sql exists. if does not:
    — set diesel
    — create db
    — create table with 3 fields
{
 image: string
 description: string
 date: string
}
→ add file path to "image", comment to "description" and date.now() to "date" of db.sql

- ```$ suiwei remember --database db.sql```
→ takes all lines from db.sql and prints them in shell



feature requests:
- flag ```--dir cache```
- command ```$ suiwei edit``` — to edit existing data

**Comment by anton-sviridov** [comment]
```
$ wget https://picsum.photos/200/300 -O event1.jpg
$ wget https://picsum.photos/200/300 -O event2.jpg
$ wget https://picsum.photos/200/300 -O event3.jpg

$ suiwei record --file event1.jpg --comment "happy day1" --database db.sql
$ suiwei record --file event2.jpg --comment "happy day2" --database db.sql
$ suiwei record --file event3.jpg --comment "happy day3" --database db.sql

# saves file paths of "happy day1",  "happy day2",  "happy day3",
# "happy day1", "happy day2", "happy day3", 
# and dates to db.sql

# check within sql cli

$ suiwei remember --database db.sql
# 2024-07-26 happy day1 path/to/event1.jpg
# 2024-07-26 happy day2 path/to/event2.jpg
# 2024-07-26 happy day3 path/to/event3.jpg
```

**Comment by anton-sviridov** [comment]
finished
